# Generated by Django 2.2.6 on 2019-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
